# Generated by Django 4.2.1 on 2023-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("count", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=100)),
                ("free_delivery", models.BooleanField(default=False)),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
