# Generated by Django 4.2.1 on 2023-05-12 15:43

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_tag_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default=1, upload_to=products.models.upload_category_photo_path
            ),
            preserve_default=False,
        ),
    ]
