# Generated by Django 4.2.1 on 2023-06-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_specification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_limited",
            field=models.BooleanField(default=False),
        ),
    ]
