# Generated by Django 4.2.1 on 2023-06-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_product_is_limited"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=100)),
                ("date_from", models.DateTimeField(auto_now_add=True)),
                ("date_to", models.DateTimeField()),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
