version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "megano/manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
