# Generated by Django 4.2.1 on 2023-06-07 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
    ]
