# Generated by Django 4.2.1 on 2023-05-06 17:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                null=True, upload_to=accounts.models.upload_avatar_path
            ),
        ),
    ]
